### ISSUE TITLE
[PE-D][Tester D] ImmuniMate button

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T08-1/tp#137]
![image.png](https://raw.githubusercontent.com/zhuuyicheng/ped/main/files/a677af4c-b25d-490e-b896-3950cfc97b3c.png)
(image of ImmuniMate button in application)

The ImmuniMate button at the top left corner of the application changes colour when hovering a mouse over it. This may lead users into thinking it is a clickable button, but nothing happens when clicking on it. You may want to consider removing it completely as it does not serve any purpose at the moment, as the name "ImmuniMate" already appears at the top left hand corner of the application as the application name.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zhuuyicheng/ped#1

**Comment by jovantanyk** [comment]
Double issue covered by #150
