### ISSUE TITLE
[PE-D][Tester B] UserGuide create a patient profile: create wrong example command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-1/tp#138]
`create ic/S0123456A n/Jane Doe hp/87654321 a/311, Clementi Ave 2, #02-25 dob/01-01-1990 s/F st/PENDING e/janed@example.com bt/A+`
Under: UserGuide.pdf#creating-a-patient-profile-create

Error: `Date of birth should be in the format of YYYY-MM-DD, and it should not be blank.`

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: camille-readbean/ped#1

**Comment by laney0808** [comment]
same as #158
