### ISSUE TITLE
[PE-D][Tester B] deleteinfo have invalid example

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T08-1/tp#142]
![image.png](https://raw.githubusercontent.com/camille-readbean/ped/main/files/b8fb6485-bc9b-4473-a88a-9689a518dc1d.png)

`deleteinfo S1234567Ae/`

```
Invalid command format! 
deleteinfo:
Deletes the information of the person identified by NRIC.
Parameters: NRIC, fields to be deleted
Example: deleteinfo S1234567Be/
```

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: camille-readbean/ped#3

**Comment by laney0808** [comment]
same as #161
