### ISSUE TITLE
[PE-D][Tester D] Incorrect command format provided in application

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-1/tp#165]
![image.png](https://raw.githubusercontent.com/zhuuyicheng/ped/main/files/dd8d219a-39d2-45ef-a057-65987c4dbf3f.png)

(command format provided after an invalid deleteinfo command)

The example command format provided does not work properly, as the "e/" field is placed directly behind the NRIC with no space. Please add a space between the "S1234567B" and "e/" for the command format to work as intended.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: zhuuyicheng/ped#6

**Comment by laney0808** [comment]
same as #161
