### ISSUE TITLE
[PE-D][Tester A] Cluster command gives the wrong error message when given large inputs

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T08-1/tp#168]
Command:
`cluster 9223372036854775807 a/Serangoon d/dengue`

When given a really large cluster size, the program returns an error message that is not fitting of the situation as the issue lies not in the command format.
This is probably caused by a validation exception but it isn't sufficiently distinguished.

![bug 10.png](https://raw.githubusercontent.com/Joseph31416/ped/main/files/c3d0169d-752d-47a1-ac57-dd4211f5ac60.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Joseph31416/ped#10

**Comment by laney0808** [comment]
mentioned in #174
