### ISSUE TITLE
[PE-D][Tester B] Comma can be used for clarity in Quick start in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-1/tp#170]
Under Quick start:
> A GUI similar to the below should appear in a few seconds.

can be 
>> A GUI, similar to the below should appear in a few seconds.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: camille-readbean/ped#12

**Comment by laney0808** [comment]
Nonsense
