### ISSUE TITLE
[PE-D][Tester A] Delete error message does not match the situation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-1/tp#180]
Command:
`delete T1234`

The error message classifies this as an invalid command format when instead it is an invalid input.

![bug 15.png](https://raw.githubusercontent.com/Joseph31416/ped/main/files/a5c4ff38-db82-42d8-b78e-71b5c628f6d1.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Joseph31416/ped#15

**Comment by laney0808** [comment]
Not a bug as format is already specified and it is a violation of format
