### ISSUE TITLE
Feature: Add Developer Details and Pictures

### ISSUE THREAD

**Issue by laney0808** [AY2324S2-CS2103T-T08-1/tp#4]
Add developer's own details and pictures in AboutUs
Update README to briefly describe the project

**Comment by jovantanyk** [comment]
Features and issues not added yet:
- [ ] README.md CI banners not pointing to own project
- [ ] README.md traces of AB3 remain 
- [ ] AboutUs.md src="images/user_name_in_lower_case.png" missing for some members
- [ ] _config.yml needs to be updated
Assigned to @jovantanyk to fix
